# Generated by Django 2.2.7 on 2020-01-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=20)),
                ('flight_destination', models.CharField(max_length=20)),
                ('flight_price', models.CharField(max_length=20)),
            ],
        ),
    ]
